import type { NextPage } from 'next';
import Head from 'next/head';
import { Text } from '@chakra-ui/react';

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Acomode</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Text fontSize="lg">ACOMODE</Text>
    </>
  );
};

export default Home;
